jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          npm install
          npm run build
          npx netlify deploy --dir=build --site=SITE_ID --auth=NETLIFY_AUTH_TOKEN --prod=false
        env:
          CI: true
          NODE_ENV: production
